// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var component: Component {
        Component(path: path + "/component")
    }

    public struct Component {
        /// Path: `/rest/api/3/component`
        public let path: String

        /// Create component
        ///
        /// Creates a component. Use components to provide containers for issues within a project.
        /// 
        /// This operation can be accessed anonymously.
        /// 
        /// **[Permissions](#permissions) required:** *Administer projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project in which the component is created or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func post(_ body: JiraKit.ProjectComponent) -> Request<JiraKit.ProjectComponent> {
            Request(path: path, method: "POST", body: body, id: "createComponent")
        }
    }
}
