// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var serverInfo: ServerInfo {
        ServerInfo(path: path + "/serverInfo")
    }

    public struct ServerInfo {
        /// Path: `/rest/api/3/serverInfo`
        public let path: String

        /// Get Jira instance info
        ///
        /// Returns information about the Jira instance.
        /// 
        /// This operation can be accessed anonymously.
        /// 
        /// **[Permissions](#permissions) required:** None.
        public var get: Request<JiraKit.ServerInformation> {
            Request(path: path, method: "GET", id: "getServerInfo")
        }
    }
}
