// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Filter {
    public var my: My {
        My(path: path + "/my")
    }

    public struct My {
        /// Path: `/rest/api/3/filter/my`
        public let path: String

        /// Get my filters
        ///
        /// Returns the filters owned by the user. If `includeFavourites` is `true`, the user's visible favorite filters are also returned.
        /// 
        /// **[Permissions](#permissions) required:** Permission to access Jira, however, a favorite filters is only visible to the user where the filter is:
        /// 
        ///  *  owned by the user.
        ///  *  shared with a group that the user is a member of.
        ///  *  shared with a private project that the user has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.
        ///  *  shared with a public project.
        ///  *  shared with the public.
        /// 
        /// For example, if the user favorites a public filter that is subsequently made private that filter is not returned by this operation.
        public func get(expand: String? = nil, isIncludeFavourites: Bool? = nil) -> Request<[JiraKit.Filter]> {
            Request(method: "GET", url: path, query: makeGetQuery(expand, isIncludeFavourites), id: "getMyFilters")
        }

        private func makeGetQuery(_ expand: String?, _ isIncludeFavourites: Bool?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(expand, forKey: "expand")
            encoder.encode(isIncludeFavourites, forKey: "includeFavourites")
            return encoder.items
        }
    }
}
