// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.AtlassianConnect.__1 {
    public var addons: Addons {
        Addons(path: path + "/addons")
    }

    public struct Addons {
        /// Path: `/rest/atlassian-connect/1/addons`
        public let path: String
    }
}
