// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var announcementBanner: AnnouncementBanner {
        AnnouncementBanner(path: path + "/announcementBanner")
    }

    public struct AnnouncementBanner {
        /// Path: `/rest/api/3/announcementBanner`
        public let path: String

        /// Get announcement banner configuration
        ///
        /// Returns the current announcement banner configuration.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public var get: Request<JiraKit.AnnouncementBannerConfiguration> {
            Request(path: path, method: "GET", id: "getBanner")
        }

        /// Update announcement banner configuration
        ///
        /// Updates the announcement banner configuration.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func put(_ body: JiraKit.AnnouncementBannerConfigurationUpdate) -> Request<AnyJSON> {
            Request(path: path, method: "PUT", body: body, id: "setBanner")
        }
    }
}
