// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Issuetypescreenscheme {
    public var project: Project {
        Project(path: path + "/project")
    }

    public struct Project {
        /// Path: `/rest/api/3/issuetypescreenscheme/project`
        public let path: String

        /// Get issue type screen schemes for projects
        ///
        /// Returns a [paginated](#pagination) list of issue type screen schemes and, for each issue type screen scheme, a list of the projects that use it.
        /// 
        /// Only issue type screen schemes used in classic projects are returned.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func get(parameters: GetParameters) -> Request<JiraKit.PageBeanIssueTypeScreenSchemesProjects> {
            Request(method: "GET", url: path, query: parameters.asQuery, id: "getIssueTypeScreenSchemeProjectAssociations")
        }

        public struct GetParameters {
            public var startAt: Int?
            public var maxResults: Int?
            public var projectID: [Int]

            public init(startAt: Int? = nil, maxResults: Int? = nil, projectID: [Int]) {
                self.startAt = startAt
                self.maxResults = maxResults
                self.projectID = projectID
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(startAt, forKey: "startAt")
                encoder.encode(maxResults, forKey: "maxResults")
                encoder.encode(projectID, forKey: "projectId")
                return encoder.items
            }
        }

        /// Assign issue type screen scheme to project
        ///
        /// Assigns an issue type screen scheme to a project.
        /// 
        /// Issue type screen schemes can only be assigned to classic projects.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func put(_ body: JiraKit.IssueTypeScreenSchemeProjectAssociation) -> Request<AnyJSON> {
            Request(method: "PUT", url: path, body: body, id: "assignIssueTypeScreenSchemeToProject")
        }
    }
}
