// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Issue {
    public var watching: Watching {
        Watching(path: path + "/watching")
    }

    public struct Watching {
        /// Path: `/rest/api/3/issue/watching`
        public let path: String

        /// Get is watching issue bulk
        ///
        /// Returns, for the user, details of the watched status of issues from a list. If an issue ID is invalid, the returned watched status is `false`.
        /// 
        /// This operation requires the **Allow users to watch issues** option to be *ON*. This option is set in General configuration for Jira. See [Configuring Jira application options](https://confluence.atlassian.com/x/uYXKM) for details.
        /// 
        /// **[Permissions](#permissions) required:**
        /// 
        ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in
        ///  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
        public func post(_ body: JiraKit.IssueList) -> Request<JiraKit.BulkIssueIsWatching> {
            Request(method: "POST", url: path, body: body, id: "getIsWatchingIssueBulk")
        }
    }
}
