// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Project.WithProjectKeyOrID {
    public var issuesecuritylevelscheme: Issuesecuritylevelscheme {
        Issuesecuritylevelscheme(path: path + "/issuesecuritylevelscheme")
    }

    public struct Issuesecuritylevelscheme {
        /// Path: `/rest/api/3/project/{projectKeyOrId}/issuesecuritylevelscheme`
        public let path: String

        /// Get project issue security scheme
        ///
        /// Returns the [issue security scheme](https://confluence.atlassian.com/x/J4lKLg) associated with the project.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) or the *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg).
        public var get: Request<JiraKit.SecurityScheme> {
            Request(path: path, method: "GET", id: "getProjectIssueSecurityScheme")
        }
    }
}
