// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.AtlassianConnect.__1.Migration {
    public var workflow: Workflow {
        Workflow(path: path + "/workflow")
    }

    public struct Workflow {
        /// Path: `/rest/atlassian-connect/1/migration/workflow`
        public let path: String
    }
}
