// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.App.Field {
    public func fieldIDOrKey(_ fieldIDOrKey: String) -> WithFieldIDOrKey {
        WithFieldIDOrKey(path: "\(path)/\(fieldIDOrKey)")
    }

    public struct WithFieldIDOrKey {
        /// Path: `/rest/api/3/app/field/{fieldIdOrKey}`
        public let path: String
    }
}
