// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Issuesecurityschemes {
    public func issueSecuritySchemeID(_ issueSecuritySchemeID: Int) -> WithIssueSecuritySchemeID {
        WithIssueSecuritySchemeID(path: "\(path)/\(issueSecuritySchemeID)")
    }

    public struct WithIssueSecuritySchemeID {
        /// Path: `/rest/api/3/issuesecurityschemes/{issueSecuritySchemeId}`
        public let path: String
    }
}
