// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var field: Field {
        Field(path: path + "/field")
    }

    public struct Field {
        /// Path: `/rest/api/3/field`
        public let path: String

        /// Get fields
        ///
        /// Returns system and custom issue fields according to the following rules:
        /// 
        ///  *  Fields that cannot be added to the issue navigator are always returned.
        ///  *  Fields that cannot be placed on an issue screen are always returned.
        ///  *  Fields that depend on global Jira settings are only returned if the setting is enabled. That is, timetracking fields, subtasks, votes, and watches.
        ///  *  For all other fields, this operation only returns the fields that the user has permission to view (that is, the field is used in at least one project that the user has *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.)
        /// 
        /// This operation can be accessed anonymously.
        /// 
        /// **[Permissions](#permissions) required:** None.
        public var get: Request<[JiraKit.FieldDetails]> {
            Request(path: path, method: "GET", id: "getFields")
        }

        /// Create custom field
        ///
        /// Creates a custom field.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func post(_ body: JiraKit.CustomFieldDefinitionJSONBean) -> Request<JiraKit.FieldDetails> {
            Request(path: path, method: "POST", body: body, id: "createCustomField")
        }
    }
}
