// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Applicationrole {
    public func key(_ key: String) -> WithKey {
        WithKey(path: "\(path)/\(key)")
    }

    public struct WithKey {
        /// Path: `/rest/api/3/applicationrole/{key}`
        public let path: String

        /// Get application role
        ///
        /// Returns an application role.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public var get: Request<JiraKit.ApplicationRole> {
            Request(path: path, method: "GET", id: "getApplicationRole")
        }
    }
}
