// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Project.WithProjectIDOrKey {
    public var role: Role {
        Role(path: path + "/role")
    }

    public struct Role {
        /// Path: `/rest/api/3/project/{projectIdOrKey}/role`
        public let path: String

        /// Get project roles for project
        ///
        /// Returns a list of [project roles](https://confluence.atlassian.com/x/3odKLg) for the project returning the name and self URL for each role.
        /// 
        /// Note that all project roles are shared with all projects in Jira Cloud. See [Get all project roles](#api-rest-api-3-role-get) for more information.
        /// 
        /// This operation can be accessed anonymously.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for any project on the site or *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public var get: Request<[String: URL]> {
            Request(method: "GET", url: path, id: "getProjectRoles")
        }
    }
}
