// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Dashboard.WithDashboardID.Items {
    public func itemID(_ itemID: String) -> WithItemID {
        WithItemID(path: "\(path)/\(itemID)")
    }

    public struct WithItemID {
        /// Path: `/rest/api/3/dashboard/{dashboardId}/items/{itemId}`
        public let path: String
    }
}
