// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.User.Bulk {
    public var migration: Migration {
        Migration(path: path + "/migration")
    }

    public struct Migration {
        /// Path: `/rest/api/3/user/bulk/migration`
        public let path: String

        /// Get account IDs for users
        ///
        /// Returns the account IDs for the users specified in the `key` or `username` parameters. Note that multiple `key` or `username` parameters can be specified.
        /// 
        /// **[Permissions](#permissions) required:** Permission to access Jira.
        public func get(parameters: GetParameters? = nil) -> Request<[JiraKit.UserMigrationBean]> {
            Request(path: path, method: "GET", query: parameters?.asQuery, id: "bulkGetUsersMigration")
        }

        public struct GetParameters {
            public var startAt: Int64?
            public var maxResults: Int32?
            public var username: [String]?
            public var key: [String]?

            public init(startAt: Int64? = nil, maxResults: Int32? = nil, username: [String]? = nil, key: [String]? = nil) {
                self.startAt = startAt
                self.maxResults = maxResults
                self.username = username
                self.key = key
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(startAt, forKey: "startAt")
                encoder.encode(maxResults, forKey: "maxResults")
                encoder.encode(username, forKey: "username")
                encoder.encode(key, forKey: "key")
                return encoder.items
            }
        }
    }
}
