// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Priority {
    public func id(_ id: String) -> WithID {
        WithID(path: "\(path)/\(id)")
    }

    public struct WithID {
        /// Path: `/rest/api/3/priority/{id}`
        public let path: String

        /// Get priority
        ///
        /// Returns an issue priority.
        /// 
        /// **[Permissions](#permissions) required:** Permission to access Jira.
        public var get: Request<JiraKit.Priority> {
            Request(path: path, method: "GET", id: "getPriority")
        }

        /// Update priority
        ///
        /// Updates an issue priority.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func put(_ body: JiraKit.UpdatePriorityDetails) -> Request<AnyJSON> {
            Request(path: path, method: "PUT", body: body, id: "updatePriority")
        }
    }
}
