// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Mypreferences {
    public var locale: Locale {
        Locale(path: path + "/locale")
    }

    public struct Locale {
        /// Path: `/rest/api/3/mypreferences/locale`
        public let path: String

        /// Get locale
        ///
        /// Returns the locale for the user.
        /// 
        /// If the user has no language preference set (which is the default setting) or this resource is accessed anonymous, the browser locale detected by Jira is returned. Jira detects the browser locale using the *Accept-Language* header in the request. However, if this doesn't match a locale available Jira, the site default locale is returned.
        /// 
        /// This operation can be accessed anonymously.
        /// 
        /// **[Permissions](#permissions) required:** None.
        public var get: Request<JiraKit.Locale> {
            Request(method: "GET", url: path, id: "getLocale")
        }

        /// Set locale
        ///
        /// Deprecated, use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API instead.
        /// 
        /// Sets the locale of the user. The locale must be one supported by the instance of Jira.
        /// 
        /// **[Permissions](#permissions) required:** Permission to access Jira.
        @available(*, deprecated, message: "Deprecated")
        public func put(_ body: JiraKit.Locale) -> Request<AnyJSON> {
            Request(method: "PUT", url: path, body: body, id: "setLocale")
        }

        /// Delete locale
        ///
        /// Deprecated, use [ Update a user profile](https://developer.atlassian.com/cloud/admin/user-management/rest/#api-users-account-id-manage-profile-patch) from the user management REST API instead.
        /// 
        /// Deletes the locale of the user, which restores the default setting.
        /// 
        /// **[Permissions](#permissions) required:** Permission to access Jira.
        @available(*, deprecated, message: "Deprecated")
        public var delete: Request<AnyJSON> {
            Request(method: "DELETE", url: path, id: "deleteLocale")
        }
    }
}
