// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Screens {
    public var addToDefault: AddToDefault {
        AddToDefault(path: path + "/addToDefault")
    }

    public struct AddToDefault {
        /// Path: `/rest/api/3/screens/addToDefault`
        public let path: String
    }
}
