// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var fieldconfigurationscheme: Fieldconfigurationscheme {
        Fieldconfigurationscheme(path: path + "/fieldconfigurationscheme")
    }

    public struct Fieldconfigurationscheme {
        /// Path: `/rest/api/3/fieldconfigurationscheme`
        public let path: String

        /// Get all field configuration schemes
        ///
        /// Returns a [paginated](#pagination) list of field configuration schemes.
        /// 
        /// Only field configuration schemes used in classic projects are returned.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func get(parameters: GetParameters? = nil) -> Request<JiraKit.PageBeanFieldConfigurationScheme> {
            Request(method: "GET", url: path, query: parameters?.asQuery, id: "getAllFieldConfigurationSchemes")
        }

        public struct GetParameters {
            public var startAt: Int64?
            public var maxResults: Int32?
            public var id: [Int64]?

            public init(startAt: Int64? = nil, maxResults: Int32? = nil, id: [Int64]? = nil) {
                self.startAt = startAt
                self.maxResults = maxResults
                self.id = id
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(startAt, forKey: "startAt")
                encoder.encode(maxResults, forKey: "maxResults")
                encoder.encode(id, forKey: "id")
                return encoder.items
            }
        }

        /// Create field configuration scheme
        ///
        /// Creates a field configuration scheme.
        /// 
        /// This operation can only create field configuration schemes used in company-managed (classic) projects.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func post(_ body: JiraKit.UpdateFieldConfigurationSchemeDetails) -> Request<JiraKit.FieldConfigurationScheme> {
            Request(method: "POST", url: path, body: body, id: "createFieldConfigurationScheme")
        }
    }
}
