// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Project.`Type` {
    public func projectTypeKey(_ projectTypeKey: String) -> WithProjectTypeKey {
        WithProjectTypeKey(path: "\(path)/\(projectTypeKey)")
    }

    public struct WithProjectTypeKey {
        /// Path: `/rest/api/3/project/type/{projectTypeKey}`
        public let path: String

        /// Get project type by key
        ///
        /// Returns a [project type](https://confluence.atlassian.com/x/Var1Nw).
        /// 
        /// This operation can be accessed anonymously.
        /// 
        /// **[Permissions](#permissions) required:** None.
        public var get: Request<JiraKit.ProjectType> {
            Request(method: "GET", url: path, id: "getProjectTypeByKey")
        }
    }
}
