// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var attachment: Attachment {
        Attachment(path: path + "/attachment")
    }

    public struct Attachment {
        /// Path: `/rest/api/3/attachment`
        public let path: String
    }
}
