// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var uiModifications: UiModifications {
        UiModifications(path: path + "/uiModifications")
    }

    public struct UiModifications {
        /// Path: `/rest/api/3/uiModifications`
        public let path: String

        /// Get UI modifications
        ///
        /// Gets UI modifications. UI modifications can only be retrieved by Forge apps.
        /// 
        /// **[Permissions](#permissions) required:** None.
        public func get(parameters: GetParameters? = nil) -> Request<JiraKit.PageBeanUiModificationDetails> {
            Request(method: "GET", url: path, query: parameters?.asQuery, id: "getUiModifications")
        }

        public struct GetParameters {
            public var startAt: Int?
            public var maxResults: Int?
            public var expand: String?

            public init(startAt: Int? = nil, maxResults: Int? = nil, expand: String? = nil) {
                self.startAt = startAt
                self.maxResults = maxResults
                self.expand = expand
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(startAt, forKey: "startAt")
                encoder.encode(maxResults, forKey: "maxResults")
                encoder.encode(expand, forKey: "expand")
                return encoder.items
            }
        }

        /// Create UI modification
        ///
        /// Creates a UI modification. UI modification can only be created by Forge apps.
        /// 
        /// Each app can define up to 100 UI modifications. Each UI modification can define up to 1000 contexts.
        /// 
        /// **[Permissions](#permissions) required:**
        /// 
        ///  *  *None* if the UI modification is created without contexts.
        ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for one or more projects, if the UI modification is created with contexts.
        public func post(_ body: JiraKit.CreateUiModificationDetails) -> Request<JiraKit.UiModificationIdentifiers> {
            Request(method: "POST", url: path, body: body, id: "createUiModification")
        }
    }
}
