// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Workflow.Transitions {
    public func transitionID(_ transitionID: Int) -> WithTransitionID {
        WithTransitionID(path: "\(path)/\(transitionID)")
    }

    public struct WithTransitionID {
        /// Path: `/rest/api/3/workflow/transitions/{transitionId}`
        public let path: String
    }
}
