// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.UniversalAvatar.`Type`.WithType.Owner.WithOwningObjectID {
    public var avatar: Avatar {
        Avatar(path: path + "/avatar")
    }

    public struct Avatar {
        /// Path: `/rest/api/3/universal_avatar/type/{type}/owner/{owningObjectId}/avatar`
        public let path: String
    }
}
