// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.User.Email {
    public var bulk: Bulk {
        Bulk(path: path + "/bulk")
    }

    public struct Bulk {
        /// Path: `/rest/api/3/user/email/bulk`
        public let path: String

        /// Get user email bulk
        ///
        /// Returns a user's email address. This API is only available to apps approved by Atlassian, according to these [guidelines](https://community.developer.atlassian.com/t/guidelines-for-requesting-access-to-email-address/27603).
        public func get(accountID: [String]) -> Request<JiraKit.UnrestrictedUserEmail> {
            Request(method: "GET", url: path, query: makeGetQuery(accountID), id: "getUserEmailBulk")
        }

        private func makeGetQuery(_ accountID: [String]) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(accountID, forKey: "accountId")
            return encoder.items
        }
    }
}
