// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Attachment {
    public var thumbnail: Thumbnail {
        Thumbnail(path: path + "/thumbnail")
    }

    public struct Thumbnail {
        /// Path: `/rest/api/3/attachment/thumbnail`
        public let path: String
    }
}
