// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Project.WithProjectIDOrKey {
    public var restore: Restore {
        Restore(path: path + "/restore")
    }

    public struct Restore {
        /// Path: `/rest/api/3/project/{projectIdOrKey}/restore`
        public let path: String

        /// Restore deleted project
        ///
        /// Restores a project from the Jira recycle bin.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public var post: Request<JiraKit.Project> {
            Request(path: path, method: "POST", id: "restore")
        }
    }
}
