// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Project {
    public var recent: Recent {
        Recent(path: path + "/recent")
    }

    public struct Recent {
        /// Path: `/rest/api/3/project/recent`
        public let path: String

        /// Get recent projects
        ///
        /// Returns a list of up to 20 projects recently viewed by the user that are still visible to the user.
        /// 
        /// This operation can be accessed anonymously.
        /// 
        /// **[Permissions](#permissions) required:** Projects are returned only where the user has one of:
        /// 
        ///  *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
        ///  *  *Administer Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project.
        ///  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func get(expand: String? = nil) -> Request<[JiraKit.Project]> {
            Request(path: path, method: "GET", query: makeGetQuery(expand), id: "getRecent")
        }

        private func makeGetQuery(_ expand: String?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(expand, forKey: "expand")
            return encoder.items
        }
    }
}
