// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var jql: Jql {
        Jql(path: path + "/jql")
    }

    public struct Jql {
        /// Path: `/rest/api/3/jql`
        public let path: String
    }
}
