// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Screens {
    public func screenID(_ screenID: Int) -> WithScreenID {
        WithScreenID(path: "\(path)/\(screenID)")
    }

    public struct WithScreenID {
        /// Path: `/rest/api/3/screens/{screenId}`
        public let path: String

        /// Update screen
        ///
        /// Updates a screen. Only screens used in classic projects can be updated.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func put(_ body: JiraKit.UpdateScreenDetails) -> Request<JiraKit.Screen> {
            Request(path: path, method: "PUT", body: body, id: "updateScreen")
        }

        /// Delete screen
        ///
        /// Deletes a screen. A screen cannot be deleted if it is used in a screen scheme, workflow, or workflow draft.
        /// 
        /// Only screens used in classic projects can be deleted.
        public var delete: Request<Void> {
            Request(path: path, method: "DELETE", id: "deleteScreen")
        }
    }
}
