// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.AtlassianConnect.__1.App {
    public var module: Module {
        Module(path: path + "/module")
    }

    public struct Module {
        /// Path: `/rest/atlassian-connect/1/app/module`
        public let path: String
    }
}
