// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Field.WithFieldKey.Option.Suggestions {
    public var search: Search {
        Search(path: path + "/search")
    }

    public struct Search {
        /// Path: `/rest/api/3/field/{fieldKey}/option/suggestions/search`
        public let path: String

        /// Get visible issue field options
        ///
        /// Returns a [paginated](#pagination) list of options for a select list issue field that can be viewed by the user.
        /// 
        /// Note that this operation **only works for issue field select list options added by Connect apps**, it cannot be used with issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource.
        /// 
        /// **[Permissions](#permissions) required:** Permission to access Jira.
        public func get(parameters: GetParameters? = nil) -> Request<JiraKit.PageBeanIssueFieldOption> {
            Request(method: "GET", url: path, query: parameters?.asQuery, id: "getVisibleIssueFieldOptions")
        }

        public struct GetParameters {
            public var startAt: Int?
            public var maxResults: Int?
            public var projectID: Int?

            public init(startAt: Int? = nil, maxResults: Int? = nil, projectID: Int? = nil) {
                self.startAt = startAt
                self.maxResults = maxResults
                self.projectID = projectID
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(startAt, forKey: "startAt")
                encoder.encode(maxResults, forKey: "maxResults")
                encoder.encode(projectID, forKey: "projectId")
                return encoder.items
            }
        }
    }
}
