// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var screenscheme: Screenscheme {
        Screenscheme(path: path + "/screenscheme")
    }

    public struct Screenscheme {
        /// Path: `/rest/api/3/screenscheme`
        public let path: String

        /// Get screen schemes
        ///
        /// Returns a [paginated](#pagination) list of screen schemes.
        /// 
        /// Only screen schemes used in classic projects are returned.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func get(parameters: GetParameters? = nil) -> Request<JiraKit.PageBeanScreenScheme> {
            Request(method: "GET", url: path, query: parameters?.asQuery, id: "getScreenSchemes")
        }

        public struct GetParameters {
            public var startAt: Int?
            public var maxResults: Int?
            public var id: [Int]?
            public var expand: String?
            public var queryString: String?
            public var orderBy: OrderBy?

            public enum OrderBy: String, Codable, CaseIterable {
                case name
                case minusname = "-name"
                case plusname = "+name"
                case id
                case minusid = "-id"
                case plusid = "+id"
            }

            public init(startAt: Int? = nil, maxResults: Int? = nil, id: [Int]? = nil, expand: String? = nil, queryString: String? = nil, orderBy: OrderBy? = nil) {
                self.startAt = startAt
                self.maxResults = maxResults
                self.id = id
                self.expand = expand
                self.queryString = queryString
                self.orderBy = orderBy
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(startAt, forKey: "startAt")
                encoder.encode(maxResults, forKey: "maxResults")
                encoder.encode(id, forKey: "id")
                encoder.encode(expand, forKey: "expand")
                encoder.encode(queryString, forKey: "queryString")
                encoder.encode(orderBy, forKey: "orderBy")
                return encoder.items
            }
        }

        /// Create screen scheme
        ///
        /// Creates a screen scheme.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func post(_ body: JiraKit.ScreenSchemeDetails) -> Request<JiraKit.ScreenSchemeID> {
            Request(method: "POST", url: path, body: body, id: "createScreenScheme")
        }
    }
}
