// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.AtlassianConnect.__1.Addons {
    public func addonKey(_ addonKey: String) -> WithAddonKey {
        WithAddonKey(path: "\(path)/\(addonKey)")
    }

    public struct WithAddonKey {
        /// Path: `/rest/atlassian-connect/1/addons/{addonKey}`
        public let path: String
    }
}
