// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.IssueLinkType {
    public func issueLinkTypeID(_ issueLinkTypeID: String) -> WithIssueLinkTypeID {
        WithIssueLinkTypeID(path: "\(path)/\(issueLinkTypeID)")
    }

    public struct WithIssueLinkTypeID {
        /// Path: `/rest/api/3/issueLinkType/{issueLinkTypeId}`
        public let path: String

        /// Get issue link type
        ///
        /// Returns an issue link type.
        /// 
        /// To use this operation, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.
        /// 
        /// This operation can be accessed anonymously.
        /// 
        /// **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for a project in the site.
        public var get: Request<JiraKit.IssueLinkType> {
            Request(method: "GET", url: path, id: "getIssueLinkType")
        }

        /// Update issue link type
        ///
        /// Updates an issue link type.
        /// 
        /// To use this operation, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func put(_ body: JiraKit.IssueLinkType) -> Request<JiraKit.IssueLinkType> {
            Request(method: "PUT", url: path, body: body, id: "updateIssueLinkType")
        }

        /// Delete issue link type
        ///
        /// Deletes an issue link type.
        /// 
        /// To use this operation, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public var delete: Request<Void> {
            Request(method: "DELETE", url: path, id: "deleteIssueLinkType")
        }
    }
}
