// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var workflowscheme: Workflowscheme {
        Workflowscheme(path: path + "/workflowscheme")
    }

    public struct Workflowscheme {
        /// Path: `/rest/api/3/workflowscheme`
        public let path: String

        /// Get all workflow schemes
        ///
        /// Returns a [paginated](#pagination) list of all workflow schemes, not including draft workflow schemes.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func get(startAt: Int? = nil, maxResults: Int? = nil) -> Request<JiraKit.PageBeanWorkflowScheme> {
            Request(method: "GET", url: path, query: makeGetQuery(startAt, maxResults), id: "getAllWorkflowSchemes")
        }

        private func makeGetQuery(_ startAt: Int?, _ maxResults: Int?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(startAt, forKey: "startAt")
            encoder.encode(maxResults, forKey: "maxResults")
            return encoder.items
        }

        /// Create workflow scheme
        ///
        /// Creates a workflow scheme.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func post(_ body: JiraKit.WorkflowScheme) -> Request<JiraKit.WorkflowScheme> {
            Request(method: "POST", url: path, body: body, id: "createWorkflowScheme")
        }
    }
}
