// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.User {
    public var properties: Properties {
        Properties(path: path + "/properties")
    }

    public struct Properties {
        /// Path: `/rest/api/3/user/properties`
        public let path: String

        /// Get user property keys
        ///
        /// Returns the keys of all properties for a user.
        /// 
        /// Note: This operation does not access the [user properties](https://confluence.atlassian.com/x/8YxjL) created and maintained in Jira.
        /// 
        /// **[Permissions](#permissions) required:**
        /// 
        ///  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), to access the property keys on any user.
        ///  *  Access to Jira, to access the calling user's property keys.
        public func get(parameters: GetParameters? = nil) -> Request<JiraKit.PropertyKeys> {
            Request(method: "GET", url: path, query: parameters?.asQuery, id: "getUserPropertyKeys")
        }

        public struct GetParameters {
            /// Example: "5b10ac8d82e05b22cc7d4ef5"
            public var accountID: String?
            public var userKey: String?
            public var username: String?

            public init(accountID: String? = nil, userKey: String? = nil, username: String? = nil) {
                self.accountID = accountID
                self.userKey = userKey
                self.username = username
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(accountID, forKey: "accountId")
                encoder.encode(userKey, forKey: "userKey")
                encoder.encode(username, forKey: "username")
                return encoder.items
            }
        }
    }
}
