// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.AtlassianConnect.__1.Addons.WithAddonKey {
    public var properties: Properties {
        Properties(path: path + "/properties")
    }

    public struct Properties {
        /// Path: `/rest/atlassian-connect/1/addons/{addonKey}/properties`
        public let path: String

        /// Get app properties
        ///
        /// Gets all the properties of an app.
        /// 
        /// **[Permissions](#permissions) required:** Only a Connect app whose key matches `addonKey` can make this request.
        public var get: Request<JiraKit.PropertyKeys> {
            Request(path: path, method: "GET", id: "AddonPropertiesResource.getAddonProperties_get")
        }
    }
}
