// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Screens.WithScreenID.Tabs.WithTabID.Fields.WithID {
    public var move: Move {
        Move(path: path + "/move")
    }

    public struct Move {
        /// Path: `/rest/api/3/screens/{screenId}/tabs/{tabId}/fields/{id}/move`
        public let path: String

        /// Move screen tab field
        ///
        /// Moves a screen tab field.
        /// 
        /// If `after` and `position` are provided in the request, `position` is ignored.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func post(_ body: JiraKit.MoveFieldBean) -> Request<AnyJSON> {
            Request(method: "POST", url: path, body: body, id: "moveScreenTabField")
        }
    }
}
