// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Attachment.WithID {
    public var expand: Expand {
        Expand(path: path + "/expand")
    }

    public struct Expand {
        /// Path: `/rest/api/3/attachment/{id}/expand`
        public let path: String
    }
}
