// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Issuetype.WithIssueTypeID.Properties {
    public func propertyKey(_ propertyKey: String) -> WithPropertyKey {
        WithPropertyKey(path: "\(path)/\(propertyKey)")
    }

    public struct WithPropertyKey {
        /// Path: `/rest/api/3/issuetype/{issueTypeId}/properties/{propertyKey}`
        public let path: String

        /// Get issue type property
        ///
        /// Returns the key and value of the [issue type property](https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties).
        /// 
        /// This operation can be accessed anonymously.
        /// 
        /// **[Permissions](#permissions) required:**
        /// 
        ///  *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg) to get the details of any issue type.
        ///  *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) to get the details of any issue types associated with the projects the user has permission to browse.
        public var get: Request<JiraKit.EntityProperty> {
            Request(method: "GET", url: path, id: "getIssueTypeProperty")
        }

        /// Set issue type property
        ///
        /// Creates or updates the value of the [issue type property](https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties). Use this resource to store and update data against an issue type.
        /// 
        /// The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func put(_ body: AnyJSON) -> Request<AnyJSON> {
            Request(method: "PUT", url: path, body: body, id: "setIssueTypeProperty")
        }

        /// Delete issue type property
        ///
        /// Deletes the [issue type property](https://developer.atlassian.com/cloud/jira/platform/storing-data-without-a-database/#a-id-jira-entity-properties-a-jira-entity-properties).
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public var delete: Request<Void> {
            Request(method: "DELETE", url: path, id: "deleteIssueTypeProperty")
        }
    }
}
