// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Project.WithProjectIDOrKey {
    public var delete: Delete {
        Delete(path: path + "/delete")
    }

    public struct Delete {
        /// Path: `/rest/api/3/project/{projectIdOrKey}/delete`
        public let path: String

        /// Delete project asynchronously
        ///
        /// Deletes a project asynchronously.
        /// 
        /// This operation is:
        /// 
        ///  *  transactional, that is, if part of the delete fails the project is not deleted.
        ///  *  [asynchronous](#async). Follow the `location` link in the response to determine the status of the task and use [Get task](#api-rest-api-3-task-taskId-get) to obtain subsequent updates.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public var post: Request<Void> {
            Request(method: "POST", url: path, id: "deleteProjectAsynchronously")
        }
    }
}
