// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Field {
    public func fieldKey(_ fieldKey: String) -> WithFieldKey {
        WithFieldKey(path: "\(path)/\(fieldKey)")
    }

    public struct WithFieldKey {
        /// Path: `/rest/api/3/field/{fieldKey}`
        public let path: String
    }
}
