// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Workflow {
    public func entityID(_ entityID: String) -> WithEntityID {
        WithEntityID(path: "\(path)/\(entityID)")
    }

    public struct WithEntityID {
        /// Path: `/rest/api/3/workflow/{entityId}`
        public let path: String

        /// Delete inactive workflow
        ///
        /// Deletes a workflow.
        /// 
        /// The workflow cannot be deleted if it is:
        /// 
        ///  *  an active workflow.
        ///  *  a system workflow.
        ///  *  associated with any workflow scheme.
        ///  *  associated with any draft workflow scheme.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public var delete: Request<Void> {
            Request(method: "DELETE", url: path, id: "deleteInactiveWorkflow")
        }
    }
}
