// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Project.WithProjectIDOrKey {
    public var type: `Type` {
        `Type`(path: path + "/type")
    }

    public struct `Type` {
        /// Path: `/rest/api/3/project/{projectIdOrKey}/type`
        public let path: String
    }
}
