// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Issuetypescheme.WithIssueTypeSchemeID {
    public var issuetype: Issuetype {
        Issuetype(path: path + "/issuetype")
    }

    public struct Issuetype {
        /// Path: `/rest/api/3/issuetypescheme/{issueTypeSchemeId}/issuetype`
        public let path: String

        /// Add issue types to issue type scheme
        ///
        /// Adds issue types to an issue type scheme.
        /// 
        /// The added issue types are appended to the issue types list.
        /// 
        /// If any of the issue types exist in the issue type scheme, the operation fails and no issue types are added.
        /// 
        /// **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
        public func put(_ body: JiraKit.IssueTypeIDs) -> Request<AnyJSON> {
            Request(path: path, method: "PUT", body: body, id: "addIssueTypesToIssueTypeScheme")
        }
    }
}
