// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3.Issuetype {
    public func issueTypeID(_ issueTypeID: String) -> WithIssueTypeID {
        WithIssueTypeID(path: "\(path)/\(issueTypeID)")
    }

    public struct WithIssueTypeID {
        /// Path: `/rest/api/3/issuetype/{issueTypeId}`
        public let path: String
    }
}
