// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.API.__3 {
    public var customFieldOption: CustomFieldOption {
        CustomFieldOption(path: path + "/customFieldOption")
    }

    public struct CustomFieldOption {
        /// Path: `/rest/api/3/customFieldOption`
        public let path: String
    }
}
