// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct ActorInputBean: Codable {
    /// The account IDs of the users to add as default actors. This parameter accepts a comma-separated list. For example, `"user":["5b10a2844c20165700ede21g", "5b109f2e9729b51b54dc274d"]`.
    public var user: [String]?
    /// The ID of the group to add as a default actor. This parameter cannot be used with the `group` parameter This parameter accepts a comma-separated list. For example, `"groupId":["77f6ab39-e755-4570-a6ae-2d7a8df0bcb8", "0c011f85-69ed-49c4-a801-3b18d0f771bc"]`.
    public var groupID: [String]?
    /// The name of the group to add as a default actor. This parameter cannot be used with the `groupId` parameter. As a group's name can change,use of `groupId` is recommended. This parameter accepts a comma-separated list. For example, `"group":["project-admin", "jira-developers"]`.
    public var group: [String]?

    public init(user: [String]? = nil, groupID: [String]? = nil, group: [String]? = nil) {
        self.user = user
        self.groupID = groupID
        self.group = group
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.user = try values.decodeIfPresent([String].self, forKey: "user")
        self.groupID = try values.decodeIfPresent([String].self, forKey: "groupId")
        self.group = try values.decodeIfPresent([String].self, forKey: "group")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(user, forKey: "user")
        try values.encodeIfPresent(groupID, forKey: "groupId")
        try values.encodeIfPresent(group, forKey: "group")
    }
}
