// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details of a field configuration to issue type mappings.
public struct AssociateFieldConfigurationsWithIssueTypesRequest: Codable {
    /// Field configuration to issue type mappings.
    public var mappings: [FieldConfigurationToIssueTypeMapping]

    public init(mappings: [FieldConfigurationToIssueTypeMapping]) {
        self.mappings = mappings
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.mappings = try values.decode([FieldConfigurationToIssueTypeMapping].self, forKey: "mappings")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(mappings, forKey: "mappings")
    }
}
