// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct AttachmentArchiveImpl: Codable {
    /// The list of the items included in the archive.
    public var entries: [AttachmentArchiveEntry]?
    /// The number of items in the archive.
    public var totalEntryCount: Int?

    public init(entries: [AttachmentArchiveEntry]? = nil, totalEntryCount: Int? = nil) {
        self.entries = entries
        self.totalEntryCount = totalEntryCount
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.entries = try values.decodeIfPresent([AttachmentArchiveEntry].self, forKey: "entries")
        self.totalEntryCount = try values.decodeIfPresent(Int.self, forKey: "totalEntryCount")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(entries, forKey: "entries")
        try values.encodeIfPresent(totalEntryCount, forKey: "totalEntryCount")
    }
}
