// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details about an attachment.
public struct Attachment: Codable {
    /// The URL of the attachment details response.
    public var this: String?
    /// The ID of the attachment.
    public var id: String?
    /// The file name of the attachment.
    public var filename: String?
    /// Details of the user who added the attachment.
    public var author: UserDetails?
    /// The datetime the attachment was created.
    public var created: Date?
    /// The size of the attachment.
    public var size: Int?
    /// The MIME type of the attachment.
    public var mimeType: String?
    /// The content of the attachment.
    public var content: String?
    /// The URL of a thumbnail representing the attachment.
    public var thumbnail: String?

    public init(this: String? = nil, id: String? = nil, filename: String? = nil, author: UserDetails? = nil, created: Date? = nil, size: Int? = nil, mimeType: String? = nil, content: String? = nil, thumbnail: String? = nil) {
        self.this = this
        self.id = id
        self.filename = filename
        self.author = author
        self.created = created
        self.size = size
        self.mimeType = mimeType
        self.content = content
        self.thumbnail = thumbnail
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.this = try values.decodeIfPresent(String.self, forKey: "self")
        self.id = try values.decodeIfPresent(String.self, forKey: "id")
        self.filename = try values.decodeIfPresent(String.self, forKey: "filename")
        self.author = try values.decodeIfPresent(UserDetails.self, forKey: "author")
        self.created = try values.decodeIfPresent(Date.self, forKey: "created")
        self.size = try values.decodeIfPresent(Int.self, forKey: "size")
        self.mimeType = try values.decodeIfPresent(String.self, forKey: "mimeType")
        self.content = try values.decodeIfPresent(String.self, forKey: "content")
        self.thumbnail = try values.decodeIfPresent(String.self, forKey: "thumbnail")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(this, forKey: "self")
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(filename, forKey: "filename")
        try values.encodeIfPresent(author, forKey: "author")
        try values.encodeIfPresent(created, forKey: "created")
        try values.encodeIfPresent(size, forKey: "size")
        try values.encodeIfPresent(mimeType, forKey: "mimeType")
        try values.encodeIfPresent(content, forKey: "content")
        try values.encodeIfPresent(thumbnail, forKey: "thumbnail")
    }
}
