// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details of global permissions to look up and project permissions with associated projects and issues to look up.
public struct BulkPermissionsRequestBean: Codable {
    /// Project permissions with associated projects and issues to look up.
    public var projectPermissions: [BulkProjectPermissions]?
    /// Global permissions to look up.
    public var globalPermissions: [String]?
    /// The account ID of a user.
    public var accountID: String?

    public init(projectPermissions: [BulkProjectPermissions]? = nil, globalPermissions: [String]? = nil, accountID: String? = nil) {
        self.projectPermissions = projectPermissions
        self.globalPermissions = globalPermissions
        self.accountID = accountID
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.projectPermissions = try values.decodeIfPresent([BulkProjectPermissions].self, forKey: "projectPermissions")
        self.globalPermissions = try values.decodeIfPresent([String].self, forKey: "globalPermissions")
        self.accountID = try values.decodeIfPresent(String.self, forKey: "accountId")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(projectPermissions, forKey: "projectPermissions")
        try values.encodeIfPresent(globalPermissions, forKey: "globalPermissions")
        try values.encodeIfPresent(accountID, forKey: "accountId")
    }
}
