// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details about a component with a count of the issues it contains.
public struct ComponentWithIssueCount: Codable {
    /// Count of issues for the component.
    public var issueCount: Int64?
    /// The type of the assignee that is assigned to issues created with this component, when an assignee cannot be set from the `assigneeType`. For example, `assigneeType` is set to `COMPONENT_LEAD` but no component lead is set. This property is set to one of the following values:
    /// 
    ///  *  `PROJECT_LEAD` when `assigneeType` is `PROJECT_LEAD` and the project lead has permission to be assigned issues in the project that the component is in.
    ///  *  `COMPONENT_LEAD` when `assignee`Type is `COMPONENT_LEAD` and the component lead has permission to be assigned issues in the project that the component is in.
    ///  *  `UNASSIGNED` when `assigneeType` is `UNASSIGNED` and Jira is configured to allow unassigned issues.
    ///  *  `PROJECT_DEFAULT` when none of the preceding cases are true.
    public var realAssigneeType: RealAssigneeType?
    /// The user assigned to issues created with this component, when `assigneeType` does not identify a valid assignee.
    public var realAssignee: User?
    /// Whether a user is associated with `assigneeType`. For example, if the `assigneeType` is set to `COMPONENT_LEAD` but the component lead is not set, then `false` is returned.
    public var isAssigneeTypeValid: Bool?
    /// The description for the component.
    public var description: String?
    /// The URL for this count of the issues contained in the component.
    public var this: URL?
    /// The key of the project to which the component is assigned.
    public var project: String?
    /// Not used.
    public var projectID: Int64?
    /// The details of the user associated with `assigneeType`, if any. See `realAssignee` for details of the user assigned to issues created with this component.
    public var assignee: User?
    /// The nominal user type used to determine the assignee for issues created with this component. See `realAssigneeType` for details on how the type of the user, and hence the user, assigned to issues is determined. Takes the following values:
    /// 
    ///  *  `PROJECT_LEAD` the assignee to any issues created with this component is nominally the lead for the project the component is in.
    ///  *  `COMPONENT_LEAD` the assignee to any issues created with this component is nominally the lead for the component.
    ///  *  `UNASSIGNED` an assignee is not set for issues created with this component.
    ///  *  `PROJECT_DEFAULT` the assignee to any issues created with this component is nominally the default assignee for the project that the component is in.
    public var assigneeType: AssigneeType?
    /// The user details for the component's lead user.
    public var lead: User?
    /// The name for the component.
    public var name: String?
    /// The unique identifier for the component.
    public var id: String?

    /// The type of the assignee that is assigned to issues created with this component, when an assignee cannot be set from the `assigneeType`. For example, `assigneeType` is set to `COMPONENT_LEAD` but no component lead is set. This property is set to one of the following values:
    /// 
    ///  *  `PROJECT_LEAD` when `assigneeType` is `PROJECT_LEAD` and the project lead has permission to be assigned issues in the project that the component is in.
    ///  *  `COMPONENT_LEAD` when `assignee`Type is `COMPONENT_LEAD` and the component lead has permission to be assigned issues in the project that the component is in.
    ///  *  `UNASSIGNED` when `assigneeType` is `UNASSIGNED` and Jira is configured to allow unassigned issues.
    ///  *  `PROJECT_DEFAULT` when none of the preceding cases are true.
    public enum RealAssigneeType: String, Codable, CaseIterable {
        case projectDefault = "PROJECT_DEFAULT"
        case componentLead = "COMPONENT_LEAD"
        case projectLead = "PROJECT_LEAD"
        case unassigned = "UNASSIGNED"
    }

    /// The nominal user type used to determine the assignee for issues created with this component. See `realAssigneeType` for details on how the type of the user, and hence the user, assigned to issues is determined. Takes the following values:
    /// 
    ///  *  `PROJECT_LEAD` the assignee to any issues created with this component is nominally the lead for the project the component is in.
    ///  *  `COMPONENT_LEAD` the assignee to any issues created with this component is nominally the lead for the component.
    ///  *  `UNASSIGNED` an assignee is not set for issues created with this component.
    ///  *  `PROJECT_DEFAULT` the assignee to any issues created with this component is nominally the default assignee for the project that the component is in.
    public enum AssigneeType: String, Codable, CaseIterable {
        case projectDefault = "PROJECT_DEFAULT"
        case componentLead = "COMPONENT_LEAD"
        case projectLead = "PROJECT_LEAD"
        case unassigned = "UNASSIGNED"
    }

    public init(issueCount: Int64? = nil, realAssigneeType: RealAssigneeType? = nil, realAssignee: User? = nil, isAssigneeTypeValid: Bool? = nil, description: String? = nil, this: URL? = nil, project: String? = nil, projectID: Int64? = nil, assignee: User? = nil, assigneeType: AssigneeType? = nil, lead: User? = nil, name: String? = nil, id: String? = nil) {
        self.issueCount = issueCount
        self.realAssigneeType = realAssigneeType
        self.realAssignee = realAssignee
        self.isAssigneeTypeValid = isAssigneeTypeValid
        self.description = description
        self.this = this
        self.project = project
        self.projectID = projectID
        self.assignee = assignee
        self.assigneeType = assigneeType
        self.lead = lead
        self.name = name
        self.id = id
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.issueCount = try values.decodeIfPresent(Int64.self, forKey: "issueCount")
        self.realAssigneeType = try values.decodeIfPresent(RealAssigneeType.self, forKey: "realAssigneeType")
        self.realAssignee = try values.decodeIfPresent(User.self, forKey: "realAssignee")
        self.isAssigneeTypeValid = try values.decodeIfPresent(Bool.self, forKey: "isAssigneeTypeValid")
        self.description = try values.decodeIfPresent(String.self, forKey: "description")
        self.this = try values.decodeIfPresent(URL.self, forKey: "self")
        self.project = try values.decodeIfPresent(String.self, forKey: "project")
        self.projectID = try values.decodeIfPresent(Int64.self, forKey: "projectId")
        self.assignee = try values.decodeIfPresent(User.self, forKey: "assignee")
        self.assigneeType = try values.decodeIfPresent(AssigneeType.self, forKey: "assigneeType")
        self.lead = try values.decodeIfPresent(User.self, forKey: "lead")
        self.name = try values.decodeIfPresent(String.self, forKey: "name")
        self.id = try values.decodeIfPresent(String.self, forKey: "id")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(issueCount, forKey: "issueCount")
        try values.encodeIfPresent(realAssigneeType, forKey: "realAssigneeType")
        try values.encodeIfPresent(realAssignee, forKey: "realAssignee")
        try values.encodeIfPresent(isAssigneeTypeValid, forKey: "isAssigneeTypeValid")
        try values.encodeIfPresent(description, forKey: "description")
        try values.encodeIfPresent(this, forKey: "self")
        try values.encodeIfPresent(project, forKey: "project")
        try values.encodeIfPresent(projectID, forKey: "projectId")
        try values.encodeIfPresent(assignee, forKey: "assignee")
        try values.encodeIfPresent(assigneeType, forKey: "assigneeType")
        try values.encodeIfPresent(lead, forKey: "lead")
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(id, forKey: "id")
    }
}
