// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// A workflow transition rule.
public struct ConnectWorkflowTransitionRule: Codable {
    /// The ID of the transition rule.
    public var id: String
    /// The key of the rule, as defined in the Connect app descriptor.
    public var key: String
    /// A rule configuration.
    public var configuration: RuleConfiguration
    public var transition: WorkflowTransition?

    public init(id: String, key: String, configuration: RuleConfiguration, transition: WorkflowTransition? = nil) {
        self.id = id
        self.key = key
        self.configuration = configuration
        self.transition = transition
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(String.self, forKey: "id")
        self.key = try values.decode(String.self, forKey: "key")
        self.configuration = try values.decode(RuleConfiguration.self, forKey: "configuration")
        self.transition = try values.decodeIfPresent(WorkflowTransition.self, forKey: "transition")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encode(key, forKey: "key")
        try values.encode(configuration, forKey: "configuration")
        try values.encodeIfPresent(transition, forKey: "transition")
    }
}
