// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The list of features on a project.
public struct ContainerForProjectFeatures: Codable {
    /// The project features.
    public var features: [ProjectFeature]?

    public init(features: [ProjectFeature]? = nil) {
        self.features = features
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.features = try values.decodeIfPresent([ProjectFeature].self, forKey: "features")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(features, forKey: "features")
    }
}
