// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details about a created issue or subtask.
public struct CreatedIssue: Codable {
    /// The ID of the created issue or subtask.
    public var id: String?
    /// The key of the created issue or subtask.
    public var key: String?
    /// The URL of the created issue or subtask.
    public var this: String?
    /// The response code and messages related to any requested transition.
    public var transition: NestedResponse?

    public init(id: String? = nil, key: String? = nil, this: String? = nil, transition: NestedResponse? = nil) {
        self.id = id
        self.key = key
        self.this = this
        self.transition = transition
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(String.self, forKey: "id")
        self.key = try values.decodeIfPresent(String.self, forKey: "key")
        self.this = try values.decodeIfPresent(String.self, forKey: "self")
        self.transition = try values.decodeIfPresent(NestedResponse.self, forKey: "transition")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(key, forKey: "key")
        try values.encodeIfPresent(this, forKey: "self")
        try values.encodeIfPresent(transition, forKey: "transition")
    }
}
