// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details of a custom field option for a context.
public struct CustomFieldOptionUpdate: Codable {
    /// The ID of the custom field option.
    public var id: String
    /// The value of the custom field option.
    public var value: String?
    /// Whether the option is disabled.
    public var isDisabled: Bool?

    public init(id: String, value: String? = nil, isDisabled: Bool? = nil) {
        self.id = id
        self.value = value
        self.isDisabled = isDisabled
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(String.self, forKey: "id")
        self.value = try values.decodeIfPresent(String.self, forKey: "value")
        self.isDisabled = try values.decodeIfPresent(Bool.self, forKey: "disabled")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encodeIfPresent(value, forKey: "value")
        try values.encodeIfPresent(isDisabled, forKey: "disabled")
    }
}
