// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The default value for a User Picker (multiple) custom field.
public struct CustomFieldContextDefaultValueMultiUserPicker: Codable {
    /// The ID of the context.
    public var contextID: String
    /// The IDs of the default users.
    public var accountIDs: [String]
    public var type: String

    public init(contextID: String, accountIDs: [String], type: String) {
        self.contextID = contextID
        self.accountIDs = accountIDs
        self.type = type
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.contextID = try values.decode(String.self, forKey: "contextId")
        self.accountIDs = try values.decode([String].self, forKey: "accountIds")
        self.type = try values.decode(String.self, forKey: "type")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(contextID, forKey: "contextId")
        try values.encode(accountIDs, forKey: "accountIds")
        try values.encode(type, forKey: "type")
    }
}
