// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The default value for a single select custom field.
public struct CustomFieldContextDefaultValueSingleOption: Codable {
    /// The ID of the context.
    public var contextID: String
    /// The ID of the default option.
    public var optionID: String
    public var type: String

    public init(contextID: String, optionID: String, type: String) {
        self.contextID = contextID
        self.optionID = optionID
        self.type = type
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.contextID = try values.decode(String.self, forKey: "contextId")
        self.optionID = try values.decode(String.self, forKey: "optionId")
        self.type = try values.decode(String.self, forKey: "type")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(contextID, forKey: "contextId")
        try values.encode(optionID, forKey: "optionId")
        try values.encode(type, forKey: "type")
    }
}
