// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The default text for a text area custom field.
public struct CustomFieldContextDefaultValueTextArea: Codable {
    /// The default text. The maximum length is 32767 characters.
    public var text: String?
    public var type: String

    public init(text: String? = nil, type: String) {
        self.text = text
        self.type = type
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.text = try values.decodeIfPresent(String.self, forKey: "text")
        self.type = try values.decode(String.self, forKey: "type")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(text, forKey: "text")
        try values.encode(type, forKey: "type")
    }
}
