// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The default value for a multiple group picker custom field.
public struct CustomFieldContextDefaultValueMultipleGroupPicker: Codable {
    /// The ID of the context.
    public var contextID: String
    /// The IDs of the default groups.
    public var groupIDs: [String]
    public var type: String

    public init(contextID: String, groupIDs: [String], type: String) {
        self.contextID = contextID
        self.groupIDs = groupIDs
        self.type = type
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.contextID = try values.decode(String.self, forKey: "contextId")
        self.groupIDs = try values.decode([String].self, forKey: "groupIds")
        self.type = try values.decode(String.self, forKey: "type")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(contextID, forKey: "contextId")
        try values.encode(groupIDs, forKey: "groupIds")
        try values.encode(type, forKey: "type")
    }
}
