// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The list of gadgets on the dashboard.
public struct DashboardGadgetResponse: Codable {
    /// The list of gadgets.
    public var gadgets: [DashboardGadget]

    public init(gadgets: [DashboardGadget]) {
        self.gadgets = gadgets
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.gadgets = try values.decode([DashboardGadget].self, forKey: "gadgets")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(gadgets, forKey: "gadgets")
    }
}
