// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct EntityPropertyDetails: Codable {
    /// The entity property ID.
    ///
    /// Example: 123
    public var entityID: Double
    /// The entity property key.
    ///
    /// Example: "mykey"
    public var key: String
    /// The new value of the entity property.
    ///
    /// Example: "newValue"
    public var value: String

    public init(entityID: Double, key: String, value: String) {
        self.entityID = entityID
        self.key = key
        self.value = value
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.entityID = try values.decode(Double.self, forKey: "entityId")
        self.key = try values.decode(String.self, forKey: "key")
        self.value = try values.decode(String.self, forKey: "value")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(entityID, forKey: "entityId")
        try values.encode(key, forKey: "key")
        try values.encode(value, forKey: "value")
    }
}
