// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details about a failed webhook.
public struct FailedWebhook: Codable {
    /// The webhook ID, as sent in the `X-Atlassian-Webhook-Identifier` header with the webhook.
    public var id: String
    /// The webhook body.
    public var body: String?
    /// The original webhook destination.
    public var url: String
    /// The time the webhook was added to the list of failed webhooks (that is, the time of the last failed retry).
    public var failureTime: Int64

    public init(id: String, body: String? = nil, url: String, failureTime: Int64) {
        self.id = id
        self.body = body
        self.url = url
        self.failureTime = failureTime
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decode(String.self, forKey: "id")
        self.body = try values.decodeIfPresent(String.self, forKey: "body")
        self.url = try values.decode(String.self, forKey: "url")
        self.failureTime = try values.decode(Int64.self, forKey: "failureTime")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(id, forKey: "id")
        try values.encodeIfPresent(body, forKey: "body")
        try values.encode(url, forKey: "url")
        try values.encode(failureTime, forKey: "failureTime")
    }
}
