// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// An operand that is a function. See [Advanced searching - functions reference](https://confluence.atlassian.com/x/dwiiLQ) for more information about JQL functions.
public struct FunctionOperand: Codable {
    /// The name of the function.
    public var function: String
    /// The list of function arguments.
    public var arguments: [String]

    public init(function: String, arguments: [String]) {
        self.function = function
        self.arguments = arguments
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.function = try values.decode(String.self, forKey: "function")
        self.arguments = try values.decode([String].self, forKey: "arguments")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(function, forKey: "function")
        try values.encode(arguments, forKey: "arguments")
    }
}
