// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details about a group.
public struct GroupName: Codable {
    /// The name of group.
    public var name: String?
    /// The ID of the group, which uniquely identifies the group across all Atlassian products. For example, *952d12c3-5b5b-4d04-bb32-44d383afc4b2*.
    public var groupID: String?
    /// The URL for these group details.
    public var this: URL?

    public init(name: String? = nil, groupID: String? = nil, this: URL? = nil) {
        self.name = name
        self.groupID = groupID
        self.this = this
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.name = try values.decodeIfPresent(String.self, forKey: "name")
        self.groupID = try values.decodeIfPresent(String.self, forKey: "groupId")
        self.this = try values.decodeIfPresent(URL.self, forKey: "self")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(name, forKey: "name")
        try values.encodeIfPresent(groupID, forKey: "groupId")
        try values.encodeIfPresent(this, forKey: "self")
    }
}
