// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct IDOrKeyBean: Codable {
    /// The ID of the referenced item.
    public var id: Int?
    /// The key of the referenced item.
    public var key: String?

    public init(id: Int? = nil, key: String? = nil) {
        self.id = id
        self.key = key
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.id = try values.decodeIfPresent(Int.self, forKey: "id")
        self.key = try values.decodeIfPresent(String.self, forKey: "key")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(id, forKey: "id")
        try values.encodeIfPresent(key, forKey: "key")
    }
}
