// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// A list of matched issues or errors for each JQL query, in the order the JQL queries were passed.
public struct IssueMatches: Codable {
    public var matches: [IssueMatchesForJQL]

    public init(matches: [IssueMatchesForJQL]) {
        self.matches = matches
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.matches = try values.decode([IssueMatchesForJQL].self, forKey: "matches")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(matches, forKey: "matches")
    }
}
