// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// A list of changelog IDs.
public struct IssueChangelogIDs: Codable {
    /// The list of changelog IDs.
    public var changelogIDs: [Int64]

    public init(changelogIDs: [Int64]) {
        self.changelogIDs = changelogIDs
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.changelogIDs = try values.decode([Int64].self, forKey: "changelogIds")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(changelogIDs, forKey: "changelogIds")
    }
}
