// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// An issue ID with entity property values. See [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/) for more information.
public struct IssueEntityPropertiesForMultiUpdate: Codable {
    /// The ID of the issue.
    public var issueID: Int64?
    /// Entity properties to set on the issue. The maximum length of an issue property value is 32768 characters.
    public var properties: [String: JSONNode]?

    public init(issueID: Int64? = nil, properties: [String: JSONNode]? = nil) {
        self.issueID = issueID
        self.properties = properties
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.issueID = try values.decodeIfPresent(Int64.self, forKey: "issueID")
        self.properties = try values.decodeIfPresent([String: JSONNode].self, forKey: "properties")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(issueID, forKey: "issueID")
        try values.encodeIfPresent(properties, forKey: "properties")
    }
}
