// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// List of issues and JQL queries.
public struct IssuesAndJQLQueries: Codable {
    /// A list of JQL queries.
    public var jqls: [String]
    /// A list of issue IDs.
    public var issueIDs: [Int64]

    public init(jqls: [String], issueIDs: [Int64]) {
        self.jqls = jqls
        self.issueIDs = issueIDs
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.jqls = try values.decode([String].self, forKey: "jqls")
        self.issueIDs = try values.decode([Int64].self, forKey: "issueIds")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(jqls, forKey: "jqls")
        try values.encode(issueIDs, forKey: "issueIds")
    }
}
