// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct IssuesUpdateBean: Codable {
    public var issueUpdates: [IssueUpdateDetails]?

    public init(issueUpdates: [IssueUpdateDetails]? = nil) {
        self.issueUpdates = issueUpdates
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.issueUpdates = try values.decodeIfPresent([IssueUpdateDetails].self, forKey: "issueUpdates")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(issueUpdates, forKey: "issueUpdates")
    }
}
