// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// A list of issue link type beans.
public struct IssueLinkTypes: Codable {
    /// The issue link type bean.
    public var issueLinkTypes: [IssueLinkType]?

    public init(issueLinkTypes: [IssueLinkType]? = nil) {
        self.issueLinkTypes = issueLinkTypes
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.issueLinkTypes = try values.decodeIfPresent([IssueLinkType].self, forKey: "issueLinkTypes")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(issueLinkTypes, forKey: "issueLinkTypes")
    }
}
