// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The JQL specifying the issues available in the evaluated Jira expression under the `issues` context variable.
public struct JexpIssues: Codable {
    /// The JQL query that specifies the set of issues available in the Jira expression.
    public var jql: JexpJqlIssues?

    public init(jql: JexpJqlIssues? = nil) {
        self.jql = jql
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.jql = try values.decodeIfPresent(JexpJqlIssues.self, forKey: "jql")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(jql, forKey: "jql")
    }
}
