// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct JiraExpressionsComplexityValueBean: Codable {
    /// The complexity value of the current expression.
    public var value: Int
    /// The maximum allowed complexity. The evaluation will fail if this value is exceeded.
    public var limit: Int

    public init(value: Int, limit: Int) {
        self.value = value
        self.limit = limit
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.value = try values.decode(Int.self, forKey: "value")
        self.limit = try values.decode(Int.self, forKey: "limit")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(value, forKey: "value")
        try values.encode(limit, forKey: "limit")
    }
}
