// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details of the order-by JQL clause.
public struct JqlQueryOrderByClause: Codable {
    /// The list of order-by clause fields and their ordering directives.
    public var fields: [JqlQueryOrderByClauseElement]

    public init(fields: [JqlQueryOrderByClauseElement]) {
        self.fields = fields
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.fields = try values.decode([JqlQueryOrderByClauseElement].self, forKey: "fields")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(fields, forKey: "fields")
    }
}
