// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The JQL query to sanitize for the account ID. If the account ID is null, sanitizing is performed for an anonymous user.
public struct JqlQueryToSanitize: Codable {
    /// The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*.
    public var accountID: String?
    /// The query to sanitize.
    public var query: String

    public init(accountID: String? = nil, query: String) {
        self.accountID = accountID
        self.query = query
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.accountID = try values.decodeIfPresent(String.self, forKey: "accountId")
        self.query = try values.decode(String.self, forKey: "query")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(accountID, forKey: "accountId")
        try values.encode(query, forKey: "query")
    }
}
