// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// An operand that is a JQL keyword. See [Advanced searching - keywords reference](https://confluence.atlassian.com/jiracorecloud/advanced-searching-keywords-reference-765593717.html#Advancedsearching-keywordsreference-EMPTYEMPTY) for more information about operand keywords.
public struct KeywordOperand: Codable {
    /// The keyword that is the operand value.
    public var keyword: Keyword

    /// The keyword that is the operand value.
    public enum Keyword: String, Codable, CaseIterable {
        case empty
    }

    public init(keyword: Keyword) {
        self.keyword = keyword
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.keyword = try values.decode(Keyword.self, forKey: "keyword")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(keyword, forKey: "keyword")
    }
}
