// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// List of updates for a custom fields.
public struct MultipleCustomFieldValuesUpdateDetails: Codable {
    public var updates: [MultipleCustomFieldValuesUpdate]?

    public init(updates: [MultipleCustomFieldValuesUpdate]? = nil) {
        self.updates = updates
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.updates = try values.decodeIfPresent([MultipleCustomFieldValuesUpdate].self, forKey: "updates")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(updates, forKey: "updates")
    }
}
