// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct NestedResponse: Codable {
    public var status: Int?
    /// Error messages from an operation.
    public var errorCollection: ErrorCollection?

    public init(status: Int? = nil, errorCollection: ErrorCollection? = nil) {
        self.status = status
        self.errorCollection = errorCollection
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.status = try values.decodeIfPresent(Int.self, forKey: "status")
        self.errorCollection = try values.decodeIfPresent(ErrorCollection.self, forKey: "errorCollection")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(status, forKey: "status")
        try values.encodeIfPresent(errorCollection, forKey: "errorCollection")
    }
}
