// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details of the group membership or permissions needed to receive the notification.
public struct NotificationRecipientsRestrictions: Codable {
    /// List of group memberships required to receive the notification.
    public var groups: [GroupName]?
    /// List of groupId memberships required to receive the notification.
    public var groupIDs: [String]?
    /// List of permissions required to receive the notification.
    public var permissions: [RestrictedPermission]?

    public init(groups: [GroupName]? = nil, groupIDs: [String]? = nil, permissions: [RestrictedPermission]? = nil) {
        self.groups = groups
        self.groupIDs = groupIDs
        self.permissions = permissions
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.groups = try values.decodeIfPresent([GroupName].self, forKey: "groups")
        self.groupIDs = try values.decodeIfPresent([String].self, forKey: "groupIds")
        self.permissions = try values.decodeIfPresent([RestrictedPermission].self, forKey: "permissions")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(groups, forKey: "groups")
        try values.encodeIfPresent(groupIDs, forKey: "groupIds")
        try values.encodeIfPresent(permissions, forKey: "permissions")
    }
}
