// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Projects and issue types where the status is used. Only available if the `usages` expand is requested.
public struct ProjectIssueTypes: Codable {
    /// Project ID details.
    public var project: ProjectID?
    /// IDs of the issue types
    public var issueTypes: [String]?

    public init(project: ProjectID? = nil, issueTypes: [String]? = nil) {
        self.project = project
        self.issueTypes = issueTypes
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.project = try values.decodeIfPresent(ProjectID.self, forKey: "project")
        self.issueTypes = try values.decodeIfPresent([String].self, forKey: "issueTypes")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(project, forKey: "project")
        try values.encodeIfPresent(issueTypes, forKey: "issueTypes")
    }
}
