// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// List of issue level security items in a project.
public struct ProjectIssueSecurityLevels: Codable {
    /// Issue level security items list.
    public var levels: [SecurityLevel]

    public init(levels: [SecurityLevel]) {
        self.levels = levels
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.levels = try values.decode([SecurityLevel].self, forKey: "levels")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(levels, forKey: "levels")
    }
}
