// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// List of project avatars.
public struct ProjectAvatars: Codable {
    /// List of avatars included with Jira. These avatars cannot be deleted.
    public var system: [Avatar]?
    /// List of avatars added to Jira. These avatars may be deleted.
    public var custom: [Avatar]?

    public init(system: [Avatar]? = nil, custom: [Avatar]? = nil) {
        self.system = system
        self.custom = custom
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.system = try values.decodeIfPresent([Avatar].self, forKey: "system")
        self.custom = try values.decodeIfPresent([Avatar].self, forKey: "custom")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(system, forKey: "system")
        try values.encodeIfPresent(custom, forKey: "custom")
    }
}
