// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// Details of the time tracking configuration.
public struct TimeTrackingConfiguration: Codable {
    /// The number of hours in a working day.
    public var workingHoursPerDay: Double
    /// The number of days in a working week.
    public var workingDaysPerWeek: Double
    /// The format that will appear on an issue's *Time Spent* field.
    public var timeFormat: TimeFormat
    /// The default unit of time applied to logged time.
    public var defaultUnit: DefaultUnit

    /// The format that will appear on an issue's *Time Spent* field.
    public enum TimeFormat: String, Codable, CaseIterable {
        case pretty
        case days
        case hours
    }

    /// The default unit of time applied to logged time.
    public enum DefaultUnit: String, Codable, CaseIterable {
        case minute
        case hour
        case day
        case week
    }

    public init(workingHoursPerDay: Double, workingDaysPerWeek: Double, timeFormat: TimeFormat, defaultUnit: DefaultUnit) {
        self.workingHoursPerDay = workingHoursPerDay
        self.workingDaysPerWeek = workingDaysPerWeek
        self.timeFormat = timeFormat
        self.defaultUnit = defaultUnit
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.workingHoursPerDay = try values.decode(Double.self, forKey: "workingHoursPerDay")
        self.workingDaysPerWeek = try values.decode(Double.self, forKey: "workingDaysPerWeek")
        self.timeFormat = try values.decode(TimeFormat.self, forKey: "timeFormat")
        self.defaultUnit = try values.decode(DefaultUnit.self, forKey: "defaultUnit")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(workingHoursPerDay, forKey: "workingHoursPerDay")
        try values.encode(workingDaysPerWeek, forKey: "workingDaysPerWeek")
        try values.encode(timeFormat, forKey: "timeFormat")
        try values.encode(defaultUnit, forKey: "defaultUnit")
    }
}
