// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The ID of a screen scheme.
public struct UpdateDefaultScreenScheme: Codable {
    /// The ID of the screen scheme.
    public var screenSchemeID: String

    public init(screenSchemeID: String) {
        self.screenSchemeID = screenSchemeID
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.screenSchemeID = try values.decode(String.self, forKey: "screenSchemeId")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(screenSchemeID, forKey: "screenSchemeId")
    }
}
