// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// The IDs of the screens for the screen types of the screen scheme.
public struct UpdateScreenTypes: Codable {
    /// The ID of the edit screen. To remove the screen association, pass a null.
    public var edit: String?
    /// The ID of the create screen. To remove the screen association, pass a null.
    public var create: String?
    /// The ID of the view screen. To remove the screen association, pass a null.
    public var view: String?
    /// The ID of the default screen. When specified, must include a screen ID as a default screen is required.
    public var `default`: String?

    public init(edit: String? = nil, create: String? = nil, view: String? = nil, `default`: String? = nil) {
        self.edit = edit
        self.create = create
        self.view = view
        self.default = `default`
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.edit = try values.decodeIfPresent(String.self, forKey: "edit")
        self.create = try values.decodeIfPresent(String.self, forKey: "create")
        self.view = try values.decodeIfPresent(String.self, forKey: "view")
        self.default = try values.decodeIfPresent(String.self, forKey: "default")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(edit, forKey: "edit")
        try values.encodeIfPresent(create, forKey: "create")
        try values.encodeIfPresent(view, forKey: "view")
        try values.encodeIfPresent(`default`, forKey: "default")
    }
}
