// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct WorklogIDsRequestBean: Codable {
    /// A list of worklog IDs.
    public var ids: [Int]

    public init(ids: [Int]) {
        self.ids = ids
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.ids = try values.decode([Int].self, forKey: "ids")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(ids, forKey: "ids")
    }
}
