// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

/// A workflow transition rule.
public struct WorkflowTransitionRule: Codable {
    /// The type of the transition rule.
    public var type: String
    /// EXPERIMENTAL. The configuration of the transition rule.
    public var configuration: AnyJSON?

    public init(type: String, configuration: AnyJSON? = nil) {
        self.type = type
        self.configuration = configuration
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.type = try values.decode(String.self, forKey: "type")
        self.configuration = try values.decodeIfPresent(AnyJSON.self, forKey: "configuration")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(type, forKey: "type")
        try values.encodeIfPresent(configuration, forKey: "configuration")
    }
}
